name: Node.js Package [beta]

on: [push]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[beta]')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          registry-url: https://registry.npmjs.org/
      - run: yarn prepublish-and-build
      - name: Validate version contains beta
        run: |
          version=$(jq -r .version package.json)
          echo $version | grep -q "\-beta"
      - run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: latest